import datetime
from math import floor
import autopep8
import re


class Method:
    def __init__(self, name: str, arguments: list[str]):
        self.name = name
        self.arguments = arguments

    def __str__(self):
        args = ""
        if len(self.arguments) != 0:
            args = ','.join(self.arguments)
            args = ',' + args
        return f"def {self.name}(self{args}):\n\t\t# write method body\n\t\tpass"


class Class:
    def __init__(self, name: str, base_class: str = None, add_init_method: bool = False):
        self.name = name.capitalize()
        self.base_class = base_class
        self.add_init_method = add_init_method
        self.methods = []
        self.class_variables = {}

    def __str__(self):
        class_def = ""
        init = ""
        methods = ""
        class_vars = ""

        if self.base_class is None:
            class_def = f"\nclass {self.name}:"
        else:
            class_def = f"\nclass {self.name}({self.base_class}):"

        if self.add_init_method is True:
            init = f"\n\tdef __init__(self):\n\t\t# initialise class here\n\t\tpass"

        for method in self.methods:
            methods = methods + f"\n\t{str(method)}"

        for var in self.class_variables:
            class_vars = class_vars + "\n" + var + " = " + self.class_variables[var]

        return f"{class_def}{class_vars}{init}{methods}"

    def add_method(self, method_name: str, arguments_names: list[str]):
        self.methods.append(Method(name=method_name, arguments=arguments_names))

    def add_class_variable(self, variable_name, variable_value):
        if isinstance(variable_value, str):
            value = "'" + variable_value + "'"
        else:
            value = variable_value
        self.class_variables[variable_name] = value


class Variable:
    def __init__(self, name, _value):
        self.name = name
        self.value = _value

    def __str__(self):
        if isinstance(self.value, str):
            value = "'" + self.value + "'"
        else:
            value = self.value
        return "\n"+self.name + " = " + value

    @property
    def value(self):
        return self._value

    @value.setter
    def value(self, value):
        self._value = value


# import modes
# 1 - import package
# 2 - from package import object
# 3 - from package import object as alias
# 4 - import package as alias


class CodegenTool:
    def __init__(self, output_file: str = None, override: bool = True):
        # create a new codegen tool
        mode = 'a+'
        if override is True:
            mode = 'w'
        if output_file is None:
            output_file = 'codegen_output' + str(floor(datetime.datetime.now().timestamp())) + ".py"
            override = True

        is_valid_file_name = re.match("\w+.py$", output_file)

        if is_valid_file_name is None:
            raise Exception('File is not a python file')
        with open(output_file, mode) as f:
            self.output_file = output_file
            if override is True:
                f.write('# This file was generated by CodegenTool')
            self.format_file()

    def import_package(self, mode=1, **kwargs):
        if mode == 1:
            statement = f"import {kwargs['package']}"
        elif mode == 2:
            statement = f"from {kwargs['package']} import {kwargs['object']}"
        elif mode == 3:
            statement = f"from {kwargs['package']} import {kwargs['object']} as {kwargs['alias']}"
        elif mode == 4:
            statement = f"import {kwargs['package']} as {kwargs['alias']}"
        else:
            raise Exception("Unrecognised import mode")

        with open(self.output_file, 'a+') as f:
            f.write(f"\n{statement}")
            self.format_file()

    def write_class(self, _class: Class):
        with open(self.output_file, 'a+') as f:
            f.write(str(_class))
            self.format_file()

    def write_variable(self, variable: Variable):
        with open(self.output_file, 'a+') as f:
            f.write(str(variable))
            self.format_file()

    def format_file(self):
        autopep8.fix_file(self.output_file)


if __name__ == '__main__':
    codegen = CodegenTool()
    var = Variable(name='a', _value='23')
    c = Class(name='NewException', base_class='Exception', add_init_method=True)
    c.add_method(method_name='get_message', arguments_names=[])
    c.add_method(method_name='another_method', arguments_names=['message'])
    codegen.import_package(mode=2, package='datetime', object='datetime')
    codegen.write_variable(var)
    codegen.write_class(c)

