# This file was generated by CodegenTool
from datetime import datetime
a = '23'
class Newexception(Exception):
	def __init__(self):
		# initialise class here
		pass
	def get_message(self):
		# write method body
		pass
	def another_method(self,message):
		# write method body
		pass